### ISSUE TITLE
Add progress bar as console output

### ISSUE THREAD

**Issue by graphixillusion** [Patty-OFurniture/TorrentFiller#1]
This is a great utility! Is it possible to add a progress bar to the console output instead the super long current output with the hashes?

**Comment by Patty-OFurniture** [comment]
Wow, someone actually found and used this.  Very surprised, although I suppose I shouldn't be.

Of course the output is too cluttered right now, mostly just for debugging.  I suppose I could do info/warning/error levels.

And then per .torrent do a file progress.  I'll probably do this soon.

**Comment by graphixillusion** [comment]
Great! For now i'm not a net developer but i managed to recompile the source hiding all the pieces/sha1 output from the console

**Comment by Patty-OFurniture** [comment]
Well, I goofed around a bit and added a verbose (-v) option, and a minimal progress bar.
